CREATE DATABASE IF NOT EXISTS depart_store;

USE depart_store;

CREATE TABLE VIPcustomers(
	id INT NOT NULL AUTO_INCREMENT,
	Firstname VARCHAR(20) NOT NULL,
	Lastname VARCHAR(20) NOT NULL, 
    Phone VARCHAR(20) NOT NULL,
    Goods VARCHAR(20) NOT NULL,
	Amount INT(10) NOT NULL,
    BOOKING_DATE DATETIME DEFAULT CURRENT_TIMESTAMP,	
	PRIMARY KEY (ID)
)Engine=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=latin1;


INSERT INTO  VIPcustomers(Firstname, Lastname, Phone, Goods , Amount , BOOKING_DATE) VALUES ("JIRAMETH", "WANNASIWAPORN", "0994989885" ,  "TOOTHPASTE" , "10", CURRENT_TIMESTAMP);
